### ISSUE TITLE
[BUG] import error when importing mypy_boto3_dynamodb.DynamoDBClient on version 1.17.72

### ISSUE THREAD

**Issue by ksilverwall** [vemel/mypy_boto3_builder#75]
**Describe the bug**
import error when execute code

**To Reproduce**

1. use this docker container'

```
FROM python:3.8

RUN pip install --upgrade pip

RUN pip install mypy boto3
RUN pip install 'boto3-stubs[dynamodb] == 1.17.72'
```

2.  Run the following code sample

```python
from mypy_boto3_dynamodb import DynamoDBClient

print('Success')
```

3. Actual output

```
Creating boto3-stubs-bug_run_run ... done
Traceback (most recent call last):
  File "./index.py", line 1, in <module>
    from mypy_boto3_dynamodb import DynamoDBClient
  File "/usr/local/lib/python3.8/site-packages/mypy_boto3_dynamodb/__init__.py", line 40, in <module>
    from .client import DynamoDBClient
  File "/usr/local/lib/python3.8/site-packages/mypy_boto3_dynamodb/client.py", line 34, in <module>
    from .paginator import (
ImportError: cannot import name 'TableExistsWaiter' from 'mypy_boto3_dynamodb.paginator' (/usr/local/lib/python3.8/site-packages/mypy_boto3_dynamodb/paginator.py)
ERROR: 1
```

**Expected output**

```
SUCCESS
```

**Additional context**

on version 1.17.71, works, it is 1.17.72 problem
Test environment: Docker version 20.10.5, build 55c4c88

**Comment by GrzegorzKowalik** [comment]
Same thing with 
```ImportError: cannot import name 'BucketExistsWaiter' from 'mypy_boto3_s3.paginator'```

Works with 1.17.71

**Comment by dan-hook** [comment]
A comment I made on another bug reporting this issue:
 I don't know in which version this changed, but in 1.17.64.2 we see that mypy_boto3_s3.client imports waiters like this:

`from mypy_boto3_s3.waiter import ( BucketExistsWaiter, BucketNotExistsWaiter, ObjectExistsWaiter, ObjectNotExistsWaiter, )`

But in 1.17.72, the Waiter imports are incorrectly grouped with the paginator imports:
`from .paginator import ( BucketExistsWaiter, BucketNotExistsWaiter, ListMultipartUploadsPaginator, ListObjectsPaginator, ListObjectsV2Paginator, ListObjectVersionsPaginator, ListPartsPaginator, ObjectExistsWaiter, ObjectNotExistsWaiter, )`

Good to know that 1.17.71 still works.

**Comment by gitpushdashf** [comment]
Getting this as well:

```
    from mypy_boto3_s3.service_resource import Bucket
/usr/local/lib/python3.8/site-packages/mypy_boto3_s3/__init__.py:44: in <module>
    from .client import S3Client
/usr/local/lib/python3.8/site-packages/mypy_boto3_s3/client.py:33: in <module>
    from .paginator import (
E   ImportError: cannot import name 'BucketExistsWaiter' from 'mypy_boto3_s3.paginator' (/usr/local/lib/python3.8/site-packages/mypy_boto3_s3/paginator.py)
```

The previous pypi release was fine.

**Comment by vemel** [comment]
Thank you for the report!

I am releasing `1.17.72.post1` with a bug fix. Also, updated integration tests, so tests should fail on invalid imports.

**Comment by vemel** [comment]
Version `1.17.72.post1` released. Sorry for the non-working annotations, and thank you for the report and related info!

Let me know if the update works as it should.

**Comment by GrzegorzKowalik** [comment]
Seems to work great, thanks for quick fix
